# Generated by Django 3.1.2 on 2020-10-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('Coffee', 'Coffee'), ('music', 'Music'), ('Travel', 'Travel')], default='music', max_length=225),
        ),
        migrations.AddField(
            model_name='news',
            name='image_url',
            field=models.URLField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submit', 'Submit'), ('Publish', 'Publish')], default='Draft', max_length=225),
        ),
    ]
